apiVersion: apps/v1
kind: Deployment
metadata:
  name: zachariahouache
  labels:
    app: php-apache
spec:
  selector:
    matchLabels:
      app: php-apache
  template:
    metadata:
      labels:
        app: php-apache
    spec:
      containers:
      - name: php-apache
        image: zachariahouache/portfolio:latest
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: zachariahouache
spec:
  selector:
    app: php-apache
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer
